# Generated by Django 5.2.17 on 2026-08-30 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='faculty_photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
